name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login al ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build imagen
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/app_nasa_power:latest .

      - name: Push imagen
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/app_nasa_power:latest